name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Publish to GPR
        env:
          GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
          OWNER: ${{ github.repository_owner }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
